name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11

      - name: Source Environment Variables
        run: |
          set -a
          source ../.env.backend
          set +a

      - name: Terraform Init
        run: |
          terraform init -backend-config="resource_group_name=${TF_VAR_state_resource_group_name}" \
            -backend-config="storage_account_name=${TF_VAR_state_storage_account_name}" \
            -backend-config="container_name=${TF_VAR_state_container_name}" \
            -backend-config="key=${TF_VAR_state_key}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
