  name: Destroy backend infra

  on:
    workflow_dispatch:

  jobs:
    terraform-destroy:
      name: 'Terraform Destroy'
      runs-on: ubuntu-latest
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VERSION: 1.3.6

      defaults:
        run:
          shell: bash
          working-directory: ./terraform

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform init
          id: init
          run: |
            set -a 
            source ../.env.backend
            terraform init \
              -backend-config="resource_group_name=$TF_VAR_state_resource_group_name" \
              -backend-config="storage_account_name=$TF_VAR_state_storage_account_name"
              
        - name: Terraform destroy
          id: destroy
          run: terraform destroy -auto-approve

        - name: Az login
          uses: azure/login@v2
          with:
            creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

        - name: Destroy backend RG
          run: |
            az keyvault delete --name bcknd-tfaz-kvault --resource-group tfaz-bcknd-rg
            az keyvault purge --name bcknd-tfaz-kvault --location norwayeast
            
            az group delete --name tfaz-bcknd-rg --yes --no-wait
            az group delete --name networkwatcherrg --yes --no-wait