name: Deploy Terraform state to backend

"on":
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy TF State to backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy TF State
        run: |
          set -a
          source .env.backend
          az login --service-principal \
            -u ${{ secrets.CLIENT_ID }} \
            -p ${{ secrets.CLIENT_SECRET }} \
            --tenant ${{ secrets.TENANT_ID }}

      - name: Create Resource Group
        run: |
          set -a
          source .env.backend
          az group create \
            -l $TF_VAR_location \
            -n $TF_VAR_state_resource_group_name

      - name: Create Storage Account
        run: |
          set -a
          source .env.backend
          az storage account create \
            -n $TF_VAR_state_storage_account_name \
            -g $TF_VAR_state_resource_group_name \
            -l $TF_VAR_location \
            --sku Standard_LRS \
            --allow-blob-public-access false

      - name: Create STG Container
        run: |
          set -a
          source .env.backend
          az storage container create \
            --name $TF_VAR_state_storage_account_container_name \
            --account-name $TF_VAR_state_storage_account_name

      - name: Create Key Vault
        run: |
          set -a
          source .env.backend
          az keyvault create \
            -n $TF_VAR_state_key_vault_name \
            -l $TF_VAR_location \
            -g $TF_VAR_state_resource_group_name \
            --enable-rbac-authorization false

      - name: Retrieve Service Principal ObjectID and Grant Access to Key Vault
        run: |
          set -a
          source .env.backend
          backend_SPNid=$(az ad sp show --id ${{ secrets.CLIENT_ID }} --query id -o tsv)

          echo "backend_SPNid: $backend_SPNid"

          az keyvault set-policy \
            -n $TF_VAR_state_key_vault_name \
            --object-id $backend_SPNid \
            --secret-permissions get list set

      - name: Create SSHKey
        run: |
          ssh-keygen -t rsa -b 4096 -f tfazlnxkey -N ""

      - name: Upload SSH public key to Key Vault
        run: |
          set -a
          source .env.backend
          az keyvault secret set \
            --vault-name $TF_VAR_state_key_vault_name \
            --name tfazlnxkeypub \
            --file tfazlnxkey.pub

      - name: Upload SSH private key to Key Vault
        run: |
          set -a
          source .env.backend
          az keyvault secret set \
            --vault-name $TF_VAR_state_key_vault_name \
            --name tfazlnxkeypriv \
            --file tfazlnxkey
